version: '2'

services:
  consul_server_1:
    image: "consul:latest"
    container_name: "consul_server_1"
    environment:
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
    networks:
      app_net:
        ipv4_address: 172.29.0.3
    command: "agent -server -bind=172.29.0.3 -client=172.29.0.3 -retry-join=172.29.0.2"

  consul_server_2:
    image: "consul:latest"
    container_name: "consul_server_2"
    ports:
      - "8600:8600"
      - "8500:8500"
    networks:
      app_net:
        ipv4_address: 172.29.0.4
    command: "agent -server -bind=172.29.0.4 -client=172.29.0.4 -retry-join=172.29.0.3 -ui"
  consul_server_3:
    image: "consul:latest"
    container_name: "consul_server_3"
    environment:
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
    networks:
      app_net:
        ipv4_address: 172.29.0.5
    command: "agent -server -bind=172.29.0.5 -client=172.29.0.5 -retry-join=172.29.0.4 -bootstrap-expect=3"
  fabio:
    image: "magiconair/fabio"
    ports:
      - "9998:9998"
      - "9999:9999"
    networks:
      app_net:
        ipv4_address: 172.29.0.6
    volumes:
      - ./fabio.properties:/etc/fabio/fabio.properties

  registrator:
    command: "sleep 5 -ip 172.29.0.7 consul://172.29.0.4:8500"
    image: "gliderlabs/registrator:latest"
    networks:
      app_net:
        ipv4_address: 172.29.0.7
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.29.0.0/24"
